services:

  # node api service
  server:
    build: .
    image: chatify-prod-image
    container_name: chatify-prod
    command: npm start
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=8080

  # mongo database service
  mongo:
    image: mongo:latest
    container_name: chat_db_container
    restart: unless-stopped
    volumes:
      - mongo_chat_data:/data/db

volumes:
  mongo_chat_data: {}
  node_modules: